[theme]
base = "light"
primaryColor = "#7C4DFF"  # Modern purple for accents
backgroundColor = "#FFFFFF"  # Clean white background
secondaryBackgroundColor = "#F5F7FF"  # Light blue-ish background for cards
textColor = "#262730"  # Darker text for better contrast
font = "sans serif"

[server]
runOnSave = true